---
name: lint-spelling
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  misspell:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        # yamllint disable-line rule:line-length
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - name: Run misspell
        # yamllint disable-line rule:line-length
        uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962  # v1.27.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_level: any
          locale: US
